spring.application.name=Ejercicio06-Frases
server.port=8084

spring.datasource.url=jdbc:postgresql://us-east-1.14c60d2a-3d4c-4cb9-9d82-d81b8d2af66b.aws.yugabyte.cloud:5433/Frase7CM3?ssl=true&sslmode=require
spring.datasource.username=admin
spring.datasource.password=AZ9YrhoqeZ3yJd2C31iDw0A8rH4VHp
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.data-source-properties.ssl=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=cristhanatz@gmail.com
spring.mail.password=cotz nzhg hdub nnmc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true